[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Allow static assets to be served directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
